### ISSUE TITLE
api still working

### ISSUE THREAD

**Issue by Jakobbenisch** [dimfalk/netatmo.weather#59]
Just a quick question: I was wondering if the api of netatmo is still the same since I get: 

Error in fetch_token() : `api.netatmo.com` is not available.

set_credentials() was successfully executed. Any ideas? Thanks, Jakob

**Comment by dimfalk** [comment]
Thanks for bringing this to my attention! Seems like there have been some changes regarding auth, probably related to #54.

However, I can reproduce this and will have to dig a little bit in order to fix this..

``` r
library(netatmo.weather)
#> 0.5.1

fetch_token()
#> Error in fetch_token(): `api.netatmo.com` is not available.
```

**Comment by dimfalk** [comment]
Ok, this should work again after a rather trivial adjustment of the public IP: 

``` r
library(netatmo.weather)
#> 0.5.2

fetch_token()
#> Note: OAuth 2.0 token successfully stored in file `.httr-oauth`.
```

**Comment by Jakobbenisch** [comment]
Thanks Dimitri, super quick :) - I have (quite poorly) written a webscraper for weatherunderground - in case you want to extend your public data repertoire - let me know. Best regards!

**Comment by dimfalk** [comment]
You're welcome!

This package hasn't reached a matured state either, but hey, as long as it gets the job done for the moment... 

Yeah, actually, I would be interested, I guess. Wrapping the WU API is still on my medium-term bucket list. I was already peering over to the deprecated [ALShum/rwunderground](https://github.com/ALShum/rwunderground) but haven't found the time to tackle this yet. Maybe in 2025.

**Comment by Jakobbenisch** [comment]
Hi Dimitri,

yeah, I guess that package worked well - here you can find my function:

https://github.com/Jakobbenisch/WU_scraper/tree/main

**Comment by dimfalk** [comment]
Great, thanks a lot for sharing! :smirk:
